[package]
name = "bencode"
description = "Efficient decoding and encoding for bencode."
keywords = ["bencode"]
version = "0.4.4"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
license-file.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
error-chain = "0.11"

[dev-dependencies]
criterion = "0.5"

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
panic = 'unwind'

[[test]]
name = "test"
path = "test/mod.rs"

[[bench]]
name = "bencode_benchmark"
harness = false