[package]
name = "peer"
version = "0.5.0"
description = "Communication with bittorrent peers via peer wire protocol"
keywords = ["peer", "wire", "protocol", "pwp", "bittorrent"]

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
license-file.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true


[dependencies]
bencode = { path = "../bencode" }
handshake = { path = "../handshake" }
util = { path = "../util" }

bytes = "0.4"
byteorder = "1.0"
crossbeam = "0.8"
error-chain = "0.11"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-timer = "0.1"
nom = "3.1"

[[test]]
name = "test"
path = "test/mod.rs"
