[package]
description = "Communication with bittorrent UDP trackers"
keywords = ["bittorrent", "tracker", "udp"]
name = "utracker"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true

[dependencies]
handshake = { path = "../handshake" }
util = { path = "../util" }

byteorder = "1"
chrono = "0.4"
futures = "0.1"
nom = "3"
rand = "0.8"
umio = "0.3"
