[package]
name = "disk"
description = "Bittorrent Infrastructure Project Disk Module"
keywords = ["filesystem", "fs", "disk"]

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
metainfo = { path = "../metainfo" }
util = { path = "../util" }

bytes = "0.4"
crossbeam = "0.8"
futures = "0.1"
futures-cpupool = "0.1"
error-chain = "0.11"
log = "0.3"
lru-cache = "0.1"

[dev-dependencies]
rand = "0.3"
tokio-core = "0.1"
criterion_bencher_compat = "0.4.0"

[[test]]
name = "test"
path = "test/mod.rs"

[[bench]]
name = "disk_benchmark"
harness = false