[package]
name = "disk"
description = "Bittorrent Infrastructure Project Disk Module"
keywords = ["filesystem", "fs", "disk"]
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true

[dependencies]
metainfo = { path = "../metainfo" }
util = { path = "../util" }

bytes = "0.4"
crossbeam = "0.8"
futures = "0.1"
futures-cpupool = "0.1"
error-chain = "0.12"
log = "0.4"
lru-cache = "0.1"

[dev-dependencies]
rand = "0.8"
tokio-core = "0.1"
criterion = "0.5"

[[test]]
name = "test"
path = "test/mod.rs"

[[bench]]
name = "disk_benchmark"
harness = false