[package]
name = "metainfo"
description = "Parsing and building of bittorrent metainfo files"
keywords = ["metainfo", "torrent", "file", "bittorrent"]

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
bencode = { path = "../bencode" }
util = { path = "../util" }
crossbeam = "0.8"
walkdir = "2.0"
error-chain = "0.11"

[dev-dependencies]
chrono = "0.4"
rand = "0.3"
pbr = "1.0"
criterion = "0.5"

[[bench]]
name = "metainfo_benchmark"
harness = false